### PR TITLE
Workaround for incompatible typings

### PR DESCRIPTION
**Pull request by stevefan1999-personal**

### CODE REVIEW

**Comment by tilmx** [comment]
Hey @stevefan1999-personal  – super big thank you for the PR!
I'm just curious what the `shrinkwrap.yaml` file is for?

Thanks!
Tilman

**Comment by stevefan1999-personal** [comment]
@tilmx I used [pnpm](https://pnpm.js.org/), `shrinkwrap.yaml` is the equivalent of `package.json.lock` or `yarn.lock`, so it's harmless I think, you could delete it if you want.

**Comment by tilmx** [comment]
Hey @stevefan1999-personal – I think it would be better to remove it. When other people without pnpm update something of the package.json, some inconsistencies might occur.

**Comment by stevefan1999-personal** [comment]
fine😞

**Comment by tilmx** [comment]
Very cool – thank you so much for the PR!

**Pull request merged**
